//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace TrackingService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrackingQueryServerSoap", Namespace="http://www.paxTracks.com/pws/webServices")]
    public partial class TrackingQueryServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOrderStatusOperationCompleted;
        
        /// <remarks/>
        public TrackingQueryServer() {
            this.Url = "http://www.paxtracks.com/pws/TrackingService.asmx";
        }
        
        /// <remarks/>
        public event getOrderStatusCompletedEventHandler getOrderStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.paxTracks.com/pws/webServices/getOrderStatus", RequestNamespace="http://www.paxTracks.com/pws/webServices", ResponseNamespace="http://www.paxTracks.com/pws/webServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getOrderStatus(string customerGroup, string userLoginName, string userPwd, string refType, string refValue) {
            object[] results = this.Invoke("getOrderStatus", new object[] {
                        customerGroup,
                        userLoginName,
                        userPwd,
                        refType,
                        refValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOrderStatus(string customerGroup, string userLoginName, string userPwd, string refType, string refValue, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOrderStatus", new object[] {
                        customerGroup,
                        userLoginName,
                        userPwd,
                        refType,
                        refValue}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetOrderStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOrderStatusAsync(string customerGroup, string userLoginName, string userPwd, string refType, string refValue) {
            this.getOrderStatusAsync(customerGroup, userLoginName, userPwd, refType, refValue, null);
        }
        
        /// <remarks/>
        public void getOrderStatusAsync(string customerGroup, string userLoginName, string userPwd, string refType, string refValue, object userState) {
            if ((this.getOrderStatusOperationCompleted == null)) {
                this.getOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderStatusOperationCompleted);
            }
            this.InvokeAsync("getOrderStatus", new object[] {
                        customerGroup,
                        userLoginName,
                        userPwd,
                        refType,
                        refValue}, this.getOrderStatusOperationCompleted, userState);
        }
        
        private void OngetOrderStatusOperationCompleted(object arg) {
            if ((this.getOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderStatusCompleted(this, new getOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getOrderStatusCompletedEventHandler(object sender, getOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
